# Generated by Django 5.1.4 on 2025-01-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.PositiveIntegerField(help_text='Ward number', unique=True)),
                ('name', models.CharField(help_text='Name of the ward', max_length=100, unique=True)),
                ('location', models.TextField(blank=True, help_text='Optional geographical location or description of the ward')),
            ],
        ),
    ]
