# Generated by Django 5.1.4 on 2025-01-03 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ward_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the ward manager', max_length=15, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Time when the manager was assigned')),
                ('user', models.OneToOneField(help_text='User associated with the ward manager', on_delete=django.db.models.deletion.CASCADE, related_name='ward_manager', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(help_text='Ward assigned to the manager', on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.ward')),
            ],
        ),
    ]
