# Generated by Django 5.1.4 on 2025-01-03 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wardmanager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the waste collector', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the waste collector', max_length=15, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Time when the collector was assigned')),
                ('active', models.BooleanField(default=True, help_text='Whether the collector is active')),
                ('user', models.OneToOneField(help_text='User associated with the waste collector', on_delete=django.db.models.deletion.CASCADE, related_name='waste_collector', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(help_text='Ward assigned to the waste collector', on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='core.ward')),
            ],
        ),
    ]
