# Generated by Django 5.1.4 on 2025-01-15 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wastecollector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the resident', max_length=200)),
                ('house_number', models.CharField(help_text='House number of the resident', max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the resident', max_length=15, null=True)),
                ('qr_code_string', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique long string for QR code verification', unique=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Time when the resident was registered')),
                ('user', models.OneToOneField(help_text='User associated with the resident', on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(help_text='Ward to which the resident belongs', on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='core.ward')),
            ],
        ),
    ]
