# Generated by Django 5.1.4 on 2025-01-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wastetype_wasteschedule_garbagecollectiontask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteschedule',
            name='waste_type',
        ),
    ]
