# Generated by Django 5.1.4 on 2025-01-17 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_wasteschedule_waste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the resident', max_length=200)),
                ('house_number', models.CharField(help_text='House number of the resident', max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the resident', max_length=15, null=True)),
                ('qr_code_string', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique long string for QR code verification', unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', help_text='Approval status', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Time when the application was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Time when the application was reviewed', null=True)),
                ('admin_comments', models.TextField(blank=True, help_text='Comments from the admin', null=True)),
                ('ward', models.ForeignKey(help_text='Ward to which the resident belongs', on_delete=django.db.models.deletion.CASCADE, related_name='resident_applications', to='core.ward')),
            ],
        ),
    ]
