# Generated by Django 5.1.4 on 2025-01-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_residentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollectionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='Date and time when the collection activity took place.')),
                ('biodegradable_waste', models.FloatField(default=0.0, help_text='Amount of biodegradable waste collected (in kg).')),
                ('recyclable_waste', models.FloatField(default=0.0, help_text='Amount of recyclable waste collected (in kg).')),
                ('non_recyclable_waste', models.FloatField(default=0.0, help_text='Amount of non-recyclable waste collected (in kg).')),
                ('hazardous_waste', models.FloatField(default=0.0, help_text='Amount of hazardous waste collected (in kg).')),
                ('notes', models.TextField(blank=True, help_text='Additional details about the collection activity.', null=True)),
                ('resident', models.ForeignKey(help_text='Resident whose waste was collected.', on_delete=django.db.models.deletion.CASCADE, related_name='waste_collections', to='core.resident')),
                ('waste_collector', models.ForeignKey(help_text='Waste collector who performed the collection.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.wastecollector')),
            ],
        ),
        migrations.DeleteModel(
            name='GarbageCollectionTask',
        ),
    ]
