# Generated by Django 5.1.4 on 2025-03-08 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_systemstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='qr_code_string',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique long string for QR code verification', unique=True),
        ),
    ]
