# Generated by Django 5.1.4 on 2025-03-16 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_resident_qr_code_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resident')),
                ('waste_collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wastecollector')),
            ],
            options={
                'unique_together': {('waste_collector', 'resident', 'date')},
            },
        ),
    ]
